apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: cosb-broker
spec:
  url: http://cosb-route-myproject.192.168.42.45.nip.io
  authInfo:
    basic:
      secretRef:
        namespace: myproject
        name: cosb-secret