apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ceph-objectstore-broker
  labels:
    app: cosb
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cosb
    spec:
      containers:
      - name: cosb
        imagePullPolicy: Always
        # imagePullPolicy: IfNotPresent
        image: bloeys/ceph-objectstore-broker:1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cosb-env
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: cosb-service
spec:
  type: NodePort
  selector:
    app: cosb
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080